from .naive_absolute import C_NaiveAbsoluteEncoding
from .naive_relative import C_NaiveRelativeEncoding
from .naive_dynamic import C_NaiveDynamicEncoding
from .naive_incremental import C_NaiveIncrementalEncoding